### ISSUE TITLE
InteractiveDateFlux notebook unexpected keyword

### ISSUE THREAD

**Issue by SEC-VT** [lkilcommons/OvationPyme#4]
In the example InteractiveDateFlux notebook, 'combine_hemispheres' is passed to an estimator.get_flux_for_time() call, but the current version doesn't support that keyword.

**Comment by lkilcommons** [comment]
I got a pull request with some Python 3 compability changes and it overwrote some of my fixes I mentioned in my previous response to you. I've readded them and the notebooks should work again. Let me know if they don't after pulling the latest version.

**Comment by SEC-VT** [comment]
The notebooks are not python 3 compatible, still using .iteritems() in the wgts ordered-dictionary (ln 108).

Fixing that, there's an error in ln 274 of ovation_prime.py because 'f107' is undefined within the scope of get_conductance(). It is defined in solar_conductance(), so I imagine the solution is to copy/past that bit of logic?

**Comment by lkilcommons** [comment]
I've pushed an update to the code that should address these two issues. 

Also, @jali7001 (**THANK YOU**) found a **major** error in the code. The error was that the model result returned for average energy was actually the energy flux. Since the expected range of values for average energy in keV and energy flux in ergs/cm/s/s are both about 0-30, I didn't notice this problem. This is a problem with the IDL code that I based OvationPyme on. It was only ever intended to calculate the energy or number flux, but it had a misleading option to calculate the electron average energy, which actually didn't do anything and just returned the energy flux. I have fixed this by adding an additional class, the AvergeEnergyEstimator, which actually correctly calculates the average energy, in the latest commit. The FluxEstimator class now only will allow you to request energy or number flux. This issue **does** affect the conductance results because conductance was calculated using the average energy following the Robinson Formula. So if you are using average energy results or conductance results you **definately** need to update your copy of the code.
